version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_seguridad
    restart: always
    environment:
      POSTGRES_DB: seguridad
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mvc-usuarios-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db        # <- usa el nombre del servicio DB
      DB_NAME: seguridad
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  db_data:
