openapi: 3.0.0
info:
  title: API de Usuarios
  description: Documentación funcional con Swagger UI
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /ping:
    get:
      summary: Verifica si el servidor está activo
      responses:
        '200':
          description: Servidor responde correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "pong"

  /usuarios:
    get:
      summary: Lista todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    correo:
                      type: string
                      example: "alan@example.com"
                    nombre:
                      type: string
                      example: "Alan"
                    app:
                      type: string
                      example: "Venegas"
                    apm:
                      type: string
                      example: "Cadena"
                    rol:
                      type: string
                      example: "admin"
                    estado:
                      type: string
                      example: "activo"
                    telefono:
                      type: string
                      example: "5512345678"

  /usuarios/nuevo:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Nuevo Usuario"
                correo:
                  type: string
                  example: "nuevo@example.com"
                password:
                  type: string
                  example: "123456"
                rol:
                  type: string
                  enum: [admin, editor, lector]
                  example: "lector"
                estado:
                  type: string
                  enum: [activo, inactivo, bloqueado]
                  example: "activo"
                app:
                  type: string
                  example: "Venegas"
                apm:
                  type: string
                  example: "Cadena"
                telefono:
                  type: string
                  example: "5512345678"
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 5
                  nombre:
                    type: string
                    example: "Nuevo Usuario"
                  correo:
                    type: string
                    example: "nuevo@example.com"
                  rol:
                    type: string
                    example: "lector"
                  estado:
                    type: string
                    example: "activo"
                  app:
                    type: string
                    example: "Venegas"
                  apm:
                    type: string
                    example: "Cadena"
                  telefono:
                    type: string
                    example: "5512345678"
