type: object
properties:
  id:
    type: integer
    example: 1
  nombre:
    type: string
    example: "Nuevo Usuario"
  correo:
    type: string
    example: "nuevo@example.com"
  rol:
    type: string
    enum: [admin, user]
    example: "user"
  estado:
    type: string
    enum: [activo, inactivo, bloqueado]
    example: "activo"
  app:
    type: string
    example: "Venegas"
  apm:
    type: string
    example: "Cadena"
  telefono:
    type: string
    example: "5512345678"

